# Generated by Django 5.0.3 on 2024-03-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('roomName', models.CharField(max_length=255)),
                ('roomUrl', models.URLField()),
                ('meetingId', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('objective', models.TextField()),
            ],
        ),
    ]
