from django.test import TestCase

# Create your tests here.
from roadmapper.roadmap import Roadmap
from roadmapper.timelinemode import TimelineMode

roadmap = Roadmap(1200, 400, colour_theme="BLUEMOUNTAIN")
roadmap.set_title("My Demo Roadmap")
roadmap.set_subtitle("Matariki Technologies Ltd")
roadmap.set_timeline(TimelineMode.WEEKLY, start="2024-01-01", number_of_items=10)

group = roadmap.add_group("Core Product Work Stream")

task = group.add_task("Base Functionality", "2024-01-01", "2024-10-31")


group1 = roadmap.add_group("Core Product Work Stream")

task1 = group1.add_task("Base Functionality", "2024-01-01", "2024-10-31")
task1.add_milestone("v.1.0", "2024-02-15")
task1.add_milestone("v.1.1", "2024-08-01")

parellel_task = task.add_parallel_task("Enhancements", "2024-11-15", "2025-03-31")
parellel_task.add_milestone("v.2.0", "2025-03-30")

task = group.add_task("Showcase #1", "2024-03-01", "2024-05-07")
task.add_parallel_task("Showcase #2", "2024-06-01", "2024-08-07")

roadmap.set_footer("Generated by Roadmapper")
roadmap.draw()
roadmap.save("demo01.png")